version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai-pipeworks-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  redis:
    image: redis:7.2-alpine
    container_name: ai-pipeworks-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  api:
    build:
      context: ./api
    container_name: ai-pipeworks-api
    environment:
      PG_DSN: ${PG_DSN}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"

